#!/bin/sh

APP_PATH="/usr/share/applications/*.desktop ~/.local/share/applications/*.desktop"
CHOICE=$(grep -h "^Name=" $APP_PATH | sed 's/^Name=//' | sort -u | dmenu -c -i -l 8 -p ">")

if [ -n "$CHOICE" ]; then 
	FILE=$(grep -l "Name=$CHOICE" $APP_PATH | head -n 1)
	dex --term "$TERMINAL" "$FILE"
fi

