#!/bin/bash

case $(printf 'shutdown\nreboot\nlock\nexit\nkill' | dmenu -i -c -l 8) in
	'shutdown') poweroff ;;
	'reboot') reboot ;;
	'lock') lockscreen ;;
	'exit') pkill dwm ;;
	'kill') ps -u $USER -o pid,comm,%cpu,%mem | dmenu -i -c -l 8 -p 'Kill:' | awk '{print $1}' | xargs -r kill ;;
	*) exit 1 ;;
esac

