#!/bin/sh

APP_PATH=""
CHOICE=$(grep -h "^Name=" /usr/share/applications/*.desktop ~/.local/share/applications/*.desktop | sed 's/^Name=//' | sort -u | dmenu -c -i -l 8 -p ">")

if [ -n "$CHOICE" ]; then 
	FILE=$(grep -l "Name=$CHOICE" /usr/share/applications/*.desktop ~/.local/share/applications/*.desktop | head -n 1)
	dex --term "$TERMINAL" "$FILE"
fi

