#!/usr/bin/env bash

FILENAME="$(date '+%s').mp4"
FILEPATH="$HOME/Movies/recordings/$FILENAME"

mkdir -p "$HOME/Movies/recordings"
AUDIO_SRC="$(pactl get-default-sink).monitor"

capture_start() {
    wf-recorder -a "$AUDIO_SRC" -f "$FILEPATH" &
    
    echo $! > /tmp/recpid
    notify-send -t 600 "Started recording to $FILENAME."
}

capture_end() {
    kill -2 "$(cat /tmp/recpid)" && rm -f /tmp/recpid
    notify-send -t 600 "Ended recording."
}

([[ -f /tmp/recpid ]] && capture_end && exit 0) || capture_start

