#!/usr/bin/env bash

FILENAME="$(date '+%s').png"
FILEPATH="$(xdg-user-dir PICTURES)/Screenshots/$FILENAME"

g=$(slurp -d)
if [ -n "$g" ]; then
	grim -g "$g" "$FILEPATH"
	notify-send "Screenshot taken!" "Saved as $FILENAME."
fi

