#!/bin/bash

CPU_TEMP=$(sensors | awk '
	/^Tdie|^Package id|^Core 0|^CPU|^temp1/ {
		gsub(/[+°C]/, "");
		for (i=1; i<=NF; i++) {
			if ($i ~ /^[0-9]+(\.[0-9]+)?$/) {
				gsub(/\..*/, "", $i);
				print $i;
				exit;
			}
		}
	}
')

MEM_FULL=$(free -m | awk '/^Mem/ { printf "%.1f", ($2)/1024 }')
MEM_USED=$(free -m | awk '/^Mem/ { printf "%.1f", ($3)/1024 }')

case $BLOCK_BUTTON in
	1) notify-send -t 7500 "Sensors" "CPU Temperature: $CPU_TEMP°C\nRAM: ${MEM_USED}GB/${MEM_FULL}GB"
esac

echo " $CPU_TEMP°C  ${MEM_USED}G/${MEM_FULL}G"

