#!/bin/bash

URL="https://wttr.in"
LOCATION=$(cat $XDG_DATA_HOME/location)
REPORT=$(curl -sf "$URL/$LOCATION?0T")

TEMP=$(echo $REPORT | grep -Eo --color=none '[0-9]+ °C' | sed 's/ °C//')

case $BLOCK_BUTTON in
	1) 
		title=$(head -1 <<< "$REPORT")
		body=$(tail -n +2 <<< "$REPORT")
		notify-send -t 5000 "$title" "$body"
	;;
esac

[[ $TEMP == '' ]] || echo "$TEMP°C"

