#!/bin/bash

BATTERY=/sys/class/power_supply/BAT0

case "$(cat $BATTERY/status)" in
	"Full")		STATUS="";;
	"Discharging")	STATUS="";;
	"Charging")	STATUS="";;
	"Not charging")	STATUS="";;
	"Unknown")	STATUS="";;
	*) exit 1 ;;
esac

PERCENT=$(cat "$BATTERY/capacity" 2>&1)

case $BLOCK_BUTTON in
	1) dmenu-system ;;
	4) brightnessctl -q s +5% ;;
	5) brightnessctl -q s 5%- ;;
esac

echo "$STATUS $PERCENT%"

