#
# Foot Config
#

title=Terminal
pad=0x0
font=FiraCode Nerd Font Mono:size=14:style=Regular
dpi-aware=yes

[cursor]
style=block
blink=yes

[mouse]
hide-when-typing=yes

[colors-dark]
alpha=0.7
background=1d2022
foreground=ebdbb2
cursor=1d2021 ebdbb2

selection-foreground=1d2021
selection-background=ebdbb2

regular0=282828
regular1=cc241d
regular2=98971a
regular3=d79921
regular4=458588
regular5=b16286
regular6=689d6a
regular7=a89984

bright0=928374
bright1=fb4934
bright2=b8bb26
bright3=fabd2f
bright4=83a598
bright5=d3869b
bright6=8ec07c
bright7=ebdbb2

