#
# Ly config
#

# General
lang = en
allow_empty_password = false
asterisk = *
auth_fails = 5
clear_password = true
default_input = login
numlock = true
shell = true
show_tty = false
save = true
service_name = ly

vi_default_mode = normal
vi_mode = false

battery_id = BAT0

auto_login_service = ly-autologin
auto_login_session = null
auto_login_user = null

path = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Keybinds
shutdown_key = F1
restart_key = F2
sleep_key = F3
hibernate_key = F4
brightness_down_key = F5
brightness_up_key = F6
show_password_key = F7

shutdown_cmd = /sbin/shutdown -a now
restart_cmd = /sbin/shutdown -r now
sleep_cmd = null
hibernate_cmd = null
brightness_down_cmd = /usr/bin/brightnessctl -q -n s 10%-
brightness_up_cmd = /usr/bin/brightnessctl -q -n s +10%

# Styling
full_color = true
fg = 0x00FFFFFF
bg = 0x00000000
text_in_center = false
hide_borders = false
border_fg = 0x00FFFFFF
box_title = null
error_bg = 0x00000000
error_fg = 0x01FF0000
blank_box = true
edge_margin = 0
margin_box_h = 2
margin_box_v = 1

bigclock = en
bigclock_12hr = false
bigclock_seconds = false
clock = %H:%M:%S

animation = colormix
animation_frame_delay = 5
animation_timeout_sec = 0

colormix_col1 = 0x0000FF00
colormix_col2 = 0x0000EE22
colormix_col3 = 0x00000000

hide_key_hints = false
hide_keyboard_locks = false
hide_version_string = false

# animation = dur_file
# dur_file_path = /etc/ly/example.dur
# dur_offset_alignment = center
# dur_x_offset = 0
# dur_y_offset = 0

