#
# Allacritty Config
#

[window]
decorations = "None"
opacity = 0.80
title = "Terminal"

[font]
size = 10
[font.normal]
family = "BigBlueTermPlus Nerd Font"
style = "Regular"

[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

[colors.normal]
black =	'#282828'
red =	'#cc241d'
green =	'#98971a'
yellow ='#d79921'
blue =	'#458588'
magenta='#b16286'
cyan =	'#689d6a'
white =	'#a89984'

[colors.bright]
black =	'#928374'
red =	'#fb4934'
green =	'#b8bb26'
yellow ='#fabd2f'
blue =	'#83a598'
magenta='#d3869b'
cyan =	'#8ec07c'
white =	'#ebdbb2'

[colors.cursor]
text = '#1D2021'
cursor = '#EBDBB2'

[colors.selection]
text = '#1D2021'
background = '#EBDBB2'

[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = true

